services:
  - type: web
    name: solarix-ai-landing
    runtime: static
    staticPublishPath: ./
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
